export const ERROR_CODES = {
  // Auth
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_EXPIRED: 'AUTH_REFRESH_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_GOOGLE_TOKEN_MISSING: 'AUTH_GOOGLE_TOKEN_MISSING',
  AUTH_GOOGLE_TOKEN_INVALID: 'AUTH_GOOGLE_TOKEN_INVALID',
  AUTH_GOOGLE_EMAIL_MISSING: 'AUTH_GOOGLE_EMAIL_MISSING',
  AUTH_GOOGLE_CALLBACK_FAILED: 'AUTH_GOOGLE_CALLBACK_FAILED',

  // Room
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_INACTIVE: 'ROOM_INACTIVE',
  ROOM_CLOSED: 'ROOM_CLOSED',
  ROOM_ACCESS_DENIED: 'ROOM_ACCESS_DENIED',
  ROOM_ALREADY_CLOSED: 'ROOM_ALREADY_CLOSED',

  // Playlist
  PLAYLIST_INVALID_URL: 'PLAYLIST_INVALID_URL',
  PLAYLIST_VIDEO_UNAVAILABLE: 'PLAYLIST_VIDEO_UNAVAILABLE',
  PLAYLIST_ITEM_NOT_FOUND: 'PLAYLIST_ITEM_NOT_FOUND',

  // Search
  SEARCH_QUERY_REQUIRED: 'SEARCH_QUERY_REQUIRED',

  // Server
  SERVER_INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
  SERVER_YOUTUBE_QUOTA_EXCEEDED: 'SERVER_YOUTUBE_QUOTA_EXCEEDED',
  SERVER_YOUTUBE_API_ERROR: 'SERVER_YOUTUBE_API_ERROR',
  SERVER_INVITE_CODE_GENERATION_FAILED: 'SERVER_INVITE_CODE_GENERATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
